/**
 * Optional model catalog imported from a local HX Edit install.
 *
 * Generated by `npm run import-res` into `public/hx-res/` (gitignored, never
 * committed). When present the viewer shows real model names, HX Edit's own
 * artwork and category colours, and parameters in their proper order and
 * units. When absent everything falls back to the neutral placeholders in
 * `categorize.ts` / `icons.tsx`, so the app works with no Line 6 data at all.
 */

export type CatalogParam = {
  id: string;
  name: string;
  type: string | null;
  min: number | null;
  max: number | null;
  default: number | null;
};

export type CatalogModel = {
  name: string | null;
  icon: string | null;
  category: number | null;
  subcategory: string | null;
  mono: boolean | null;
  stereo: boolean | null;
  load: number | null;
  loadStereo: number | null;
  params: CatalogParam[];
};

export type CatalogCategory = {
  name: string;
  shortName: string;
  color: string | null;
  icon: string | null;
};

/**
 * A HelixControls entry. `format`/`formatUnits` are printf-ish; either can be
 * a plain string, an array of literals (discrete values, indexed by the raw
 * value), or an array of range objects selected by the display value.
 */
export type ControlDef = {
  dspToDisplayScale?: number;
  isDiscrete?: boolean;
  format?: string | (string | ControlFormatRange)[];
  formatUnits?: string;
  minimumValue?: number;
  maximumValue?: number;
};

export type ControlFormatRange = {
  lowerBound: number;
  upperBound: number;
  format?: string;
  formatUnits?: string;
  unitsMultiplier?: number;
};

export type Catalog = {
  generatedAt: string;
  source: string;
  categories: Record<string, CatalogCategory>;
  models: Record<string, CatalogModel>;
  controls: Record<string, ControlDef>;
};

export const CATALOG_URL = "/hx-res/catalog.json";
export const ICON_BASE = "/hx-res/icons";

export async function loadCatalog(): Promise<Catalog | null> {
  try {
    const res = await fetch(CATALOG_URL, { cache: "force-cache" });
    if (!res.ok) return null;
    return (await res.json()) as Catalog;
  } catch {
    return null;
  }
}

/**
 * Apply one printf-style conversion (the only ones HelixControls uses:
 * %f-family with optional width/precision/plus-flag, plus a literal %%).
 */
function applyFormat(spec: string, value: number): string {
  return spec.replace(/%([+])?(?:(\d+))?(?:\.(\d+))?([fdg])|%%/g, (match, plus, _width, precision, conv) => {
    if (match === "%%") return "%";
    const digits = precision === undefined ? (conv === "d" ? 0 : 6) : Number(precision);
    let out = conv === "d" ? String(Math.round(value)) : value.toFixed(digits);
    if (plus && value >= 0) out = `+${out}`;
    return out;
  });
}

function pickRange(
  ranges: (string | ControlFormatRange)[],
  displayValue: number
): ControlFormatRange | null {
  for (const r of ranges) {
    if (typeof r === "string") continue;
    if (displayValue >= r.lowerBound && displayValue <= r.upperBound) return r;
  }
  return null;
}

/**
 * The literal choices behind a discrete control (mic models, note divisions,
 * Off/On, ...), or null if this control isn't discrete. The raw preset value
 * is the index into this list.
 */
export function discreteOptions(
  paramType: string | null | undefined,
  controls: Record<string, ControlDef> | undefined
): string[] | null {
  if (!paramType || !controls) return null;
  const def = controls[paramType];
  if (!def?.isDiscrete || !Array.isArray(def.format)) return null;
  const literals = def.format.filter((f): f is string => typeof f === "string");
  return literals.length > 0 ? literals : null;
}

const CONVERSION = /%[+]?(?:\d+)?(?:\.\d+)?[fdg]/;

/**
 * The unit that trails the number in a format string: "%.1f kHz" -> "kHz".
 *
 * Only text *after* the conversion counts. Some controls put a word in front
 * instead ("Left %.0f" for pan) — that's a directional label, not a unit, so
 * it yields "" and the reading is left to the formatted value.
 */
function unitFromFormat(spec: string): string {
  const match = spec.match(CONVERSION);
  if (!match || match.index === undefined) return "";
  return spec
    .slice(match.index + match[0].length)
    .replace(/%%/g, "%")
    .trim();
}

/**
 * The unit a parameter's *stored* value is expressed in.
 *
 * Some controls render large values in a friendlier unit — a cab High Cut of
 * 8000 shows as "8.0 kHz" via a range with `unitsMultiplier: 0.001`. An edit
 * box has to stay in one unit to be typeable, so it uses the unscaled one
 * (Hz here), which is the range that carries no multiplier.
 */
export function baseUnit(
  paramType: string | null | undefined,
  controls: Record<string, ControlDef> | undefined
): string {
  if (!paramType || !controls) return "";
  const def = controls[paramType];
  if (!def || def.isDiscrete) return "";
  if (typeof def.format === "string" || def.formatUnits) {
    return def.formatUnits ? unitFromFormat(def.formatUnits) : "";
  }
  if (Array.isArray(def.format)) {
    for (const r of def.format) {
      if (typeof r === "string") continue;
      // Skip sentinel ranges like { format: "Off" } — those are literal
      // labels for a special value, not a unit for the whole control.
      if (!r.formatUnits || !CONVERSION.test(r.formatUnits)) continue;
      if ((r.unitsMultiplier ?? 1) === 1) return unitFromFormat(r.formatUnits);
    }
  }
  return "";
}

/**
 * Factor between the stored value and the number HX Edit shows on screen
 * (a Drive stored as 0.77 displays as 7.7).
 */
export function displayScale(
  paramType: string | null | undefined,
  controls: Record<string, ControlDef> | undefined
): number {
  if (!paramType || !controls) return 1;
  return controls[paramType]?.dspToDisplayScale ?? 1;
}

/**
 * Render a raw preset value the way HX Edit would display it.
 * Returns null when the catalog can't improve on the raw value.
 */
export function formatParamValue(
  raw: unknown,
  paramType: string | null | undefined,
  controls: Record<string, ControlDef> | undefined
): string | null {
  if (raw === null || raw === undefined) return null;
  if (typeof raw === "boolean") return raw ? "On" : "Off";
  if (typeof raw !== "number" || !paramType || !controls) return null;

  const def = controls[paramType];
  if (!def) return null;

  // Discrete controls index a table of literals by the raw value
  // (e.g. mic 6 -> "160 Ribbon", sync_note 5 -> "1/4").
  if (def.isDiscrete && Array.isArray(def.format)) {
    const literals = def.format.filter((f): f is string => typeof f === "string");
    const idx = Math.round(raw);
    if (idx >= 0 && idx < literals.length) return literals[idx];
    return null;
  }

  const display = raw * (def.dspToDisplayScale ?? 1);

  if (Array.isArray(def.format)) {
    const range = pickRange(def.format, display);
    if (!range) return null;
    const spec = range.formatUnits ?? range.format;
    if (!spec) return null;
    return applyFormat(spec, display * (range.unitsMultiplier ?? 1));
  }

  const spec = def.formatUnits ?? def.format;
  if (typeof spec !== "string") return null;
  return applyFormat(spec, display);
}
